# News orgs
ALJAZEERA = 'Al Jazeera'
BBC = 'BBC'
CBC = 'CBC'
CNN = 'CNN'
GLOBE_AND_MAIL = 'Globe and Mail'
GUARDIAN = 'Guardian'
HUFF_POST = 'Huffington Post'
JPOST = 'Jerusalem Post'
NY_POST = 'New York Post'
NY_TIMES = 'New York Times'
REUTERS = 'Reuters'
RUSSIA_TODAY = 'Russia Today'
TIMES_OF_ISRAEL = 'Times of Israel'
TODAYS_ZAMAN = 'Today\'s Zaman'
USA_TODAY = 'USA Today'
